version: '3.8'
services: 
  api:
    image: golang:1.17-rc-alpine
    container_name: 'api'
    networks:
      - book_manager_net
    environment:
      - ROOT_PASS=${ROOT_PASS}
      - DATABASE=${DATABASE}
      - CGO_ENABLED=0
    ports: 
      - 8080:8080
    volumes: 
      - ./:/go/src/app
    working_dir: /go/src/app
    command: ["go", "run", "main.go"]
  db:
    image: mariadb:10.5.12
    container_name: 'db'
    networks:
      - book_manager_net
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_DATABASE=${DATABASE}
      - TZ=Asia/Tokyo
    volumes:
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
networks:
  book_manager_net:
    driver: bridge
